cmake_minimum_required(VERSION 3.16)

project(PROBLEMAS_P2 LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

add_executable(PROBLEMAS_P2 main.cpp
    funciones_p2.h funciones_p2.cpp
)

include(GNUInstallDirs)
install(TARGETS PROBLEMAS_P2
    LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
    RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}
)
