cmake_minimum_required(VERSION 3.16)

project(_PROBLEMAS_P2_ LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

add_executable(_PROBLEMAS_P2_ main.cpp
    funciones.h funciones.cpp)

include(GNUInstallDirs)
install(TARGETS _PROBLEMAS_P2_
    LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
    RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}
)
